### ISSUE TITLE
Transfer requirements from notes doc to GH Issues

### ISSUE THREAD

**Issue by pterygaphykion** [runrig-coop/rgo-early-warning-system#2]
Convert requirements from the [Project Requirements doc](https://github.com/runrig-coop/internal-notes/tree/main/projects/rgo-crop-plan-auditing#project-requirements) to github issues so we can track milestones.

**Comment by jgaehring** [comment]
I moved those requirements to a [new public repository](https://github.com/runrig-coop/open-design-workshops/tree/e45a7f7a8280a4a8263c8ecb9fed52d7a4f13f52/rgo-crop-plan-auditing), since it covers 2 separate interventions for the pilot project with RGO, this Early Warning System being only one. I figure that way it can live there for future reference and provide a broader overview of our aims at the outset of this. And as we explore other projects, it can be sort of public forum for further discussion of topics outside the scope of this repo specifically. I also added a qualification to the requirements:

> Below is an outline of proposed features for the interventions above. Although they may not be "requirements" in the strictest sense, they can serve as "gestures" towards a few potential outcomes, as we iterate on a practicable solution.

I'll try to map the better defined features from that list onto issues here, taking into account some of the more technical limitations, so it won't be a strict 1-to-1 mapping, but should provide us with a few starting points.

**Comment by jgaehring** [comment]
Okay, I added the following issues which I think are needed for the first MVP:

- #5 
- #6 
- #7 
- #8 

This does __not__ include any semi-automated submissions from the farmers themselves (eg, via SurveyStack), let alone fully automated sensor readings. Nor does it address more complex evaluation of things like distance from the central office to each farm, pending orders, etc. Those can come later, but the above features, once implemented, should be sufficient for a first MVP that we can put in users' hands. Even #7 and #8 are probably not absolutely necessary.

Should we group them into a milestone then?
